### ISSUE TITLE
WARNING: CodeQL Robocommits

### ISSUE THREAD

**Issue by gek169** [tuupola/hagl#116]
Hello! This is a warning to the maintainer of this repository.

The CodeQL people are using some tool to automatically write code and then making PRs to various free software projects.

![image](https://github.com/tuupola/hagl/assets/6974902/e4e82e02-cddf-45a2-91f6-fa0f1249d20d)
I have screenshot this from the PR they made. As you can read for yourself, they confess outright that they are automatically generating this code.

I would encourage you to _reject_ this with _extreme prejudice_ for the following reasons:
1. It is unclear what the copyright status of this code is
2. These people seem to be presenting their commits as something they are not in their messages (I.e. not auto-generated)
3. This is a form of human experimentation (if they are telling the truth) or some sort of scam (if they are not) neither of which is particularly appealing.
4. A low-level portable graphics library like HAGL likely has little need for security analysis.

They already tried to make a PR on a project I maintain and that's how I found out about them.

I would be interested to hear how you deal with them. If you end up trying whatever it is they're selling, please tell me how it turned out. 

Am I being paranoid? Perhaps. But this smells bad.
~DMHSW

**Comment by davisjam** [comment]
Hi, I'm Prof. James Davis from Purdue University. I'm part of the team conducting measurements of CodeQL on (embedded) software. The manuscript describing our results is linked in our PR on this repo (#115).

I've replied to the concerns that @gek169 raises at length [in our similar PR on the tinygl repo](https://github.com/C-Chads/tinygl/pull/29#issuecomment-1791190866), but just to be exhaustive let me say it here as well:

- `Copyright`: We don't care about copyright. Whatever you want to do with the code is fine. That's how PRs to open-source repositories work.
- `Presenting commits as not auto-generated`: We are confused about this concern. We analyzed hundreds of repos. Since we found CodeQL was helpful, we made PRs to some of the repos offering CodeQL support. We used a program to help us do that. What else should we have done...?
- `This is human experimentation`: No it is not. This is a contribution to an open-source repository on GitHub.
- `No need for security analysis`: It is hard to judge where one's open-source code is running. There are many stories of unexpected use cases that resulted in security problems down the road. This is for the maintainers' judgment, to weigh usefulness vs. annoyance factor (eg false positives). We reported expected false positive rates in the PR we opened.

> They already tried to make a PR on a project I maintain and that's how I found out about them.

Yes, we also offered a PR to a repo maintained by @gek169. They were uninterested in what we offered, and closed the PR.

> I would be interested to hear how you deal with them. If you end up trying whatever it is they're selling, please tell me how it turned out.

This is strangely antagonistic. We are not selling anything. We wrote a technical paper describing our findings. We made a PR that lets the maintainers incorporate the CodeQL tool if they find it helpful. The maintainers can judge this for themselves.

> Am I being paranoid?

I appreciate your caution, but I think it would be more constructive for you to read the technical paper, learn about CodeQL, and look at the PRs we've opened. There is nothing fishy here.

**Comment by gek169** [comment]
Hello @davisjam 
I did end up trying your CodeQL system. It didn't seem to catch anything of note but it did find a place I shadowed a variable. So... thanks for that, I guess.

Now that I have tried it, I will say this:

1. CodeQL seems to work (albeit with some unusual false positives) and does seem to catch programming errors
2. What you're doing is not what I thought you were doing. I believed you were using a program to automatically write code for repositories with little/no human intervention. You have made it explicitly clear that this is not true, and you appear to have the credibility to back it up.

I am now rescinding my warning with regards to what you're doing being a scam. HOWEVER...
1. The license of CodeQL is... spooky. After I tried it, I ended up removing it from the repository for that reason. CodeQL might WORK, it's just... I don't know if I want to have anything under that license in my codebases.
